base_url = "https://langyo.xyz"

compile_sass = true
build_search_index = false

title = "LANGYO"
description = "伊欧的个人空间站点"

[markdown]
highlight_code = true

[extra]
home_subtitle = "这里是伊欧的个人站"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
footer_recordation_text = '沪ICP备20025013号-2'
footer_recordation_text_security = '沪公网安备31011502403090号'
footer_recordation_text_security_code = '31011502403090'
footer_recordation_text_moe = '萌ICP备20255233号'

hermit_menu = [
    { link = "/posts", name = "记录" },
    { link = "/about", name = "关于" },
]

hermit_social = [
    { name = "github", link = "https://github.com/langyo" },
    { name = "email", link = "mailto:langyo.china@gmail.com" },
    { name = "bilibili", link = "https://space.bilibili.com/5741197" },
    { name = "steam", link = "https://steamcommunity.com/id/langyo_china" },
]

[extra.highlightjs]
enable = true
clipboard = true
theme = "obsidian"

[extra.disqus]
enable = false
shortname = "langyo-blog"

[extra.author]
name = "langyo"
email = "langyo.china@gmail.com"

[extra.google_analytics]
enable = true
id = "G-QHZB20Q6RQ"
