[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.publish]
script = '''
#!@duckscript

cm_run_task _publish_${1}
'''

[tasks._publish_]
private = true
extend = "_publish_docker"

[tasks._publish_docker]
private = true
script = '''
#!@duckscript

if is_windows
    exec wsl --exec docker build -t east-hydro .
    exec wsl --exec docker tag east-hydro:latest crpi-88d7shkt0yo9qvvt.cn-shanghai.personal.cr.aliyuncs.com/langyo_personal/homepage:latest
    exec wsl --exec docker push crpi-88d7shkt0yo9qvvt.cn-shanghai.personal.cr.aliyuncs.com/langyo_personal/homepage:latest
else
    exec docker build -t east-hydro .
    exec docker tag east-hydro:latest crpi-88d7shkt0yo9qvvt.cn-shanghai.personal.cr.aliyuncs.com/langyo_personal/homepage:latest
    exec docker push crpi-88d7shkt0yo9qvvt.cn-shanghai.personal.cr.aliyuncs.com/langyo_personal/homepage:latest
end
'''
