[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.publish]
script = '''
#!@duckscript

cm_run_task _publish_${1}
'''

[tasks._publish_]
private = true
extend = "_publish_podman"

[tasks._publish_docker]
private = true
script = '''
#!@duckscript

exec docker build -t homepage .
exec docker tag homepage:latest crpi-88d7shkt0yo9qvvt.cn-shanghai.personal.cr.aliyuncs.com/langyo_personal/homepage:latest
exec docker push crpi-88d7shkt0yo9qvvt.cn-shanghai.personal.cr.aliyuncs.com/langyo_personal/homepage:latest
'''

[tasks._publish_podman]
private = true
script = '''
#!@duckscript

exec podman build -t homepage -f ./dockerfile
exec podman tag homepage:latest crpi-88d7shkt0yo9qvvt.cn-shanghai.personal.cr.aliyuncs.com/langyo_personal/homepage:latest
exec podman push crpi-88d7shkt0yo9qvvt.cn-shanghai.personal.cr.aliyuncs.com/langyo_personal/homepage:latest
'''
